<?php
/** Wordpress Header
 * 
 * Plugin Name: BRIDGE phpBB & WordPress
 * Plugin URI: http://www.mssti.com/
 * Description: Synchronize users from phpBB 3.0.x in WordPress.
 * Version: 0.0.4
 * Author: leviatan21
 * Author URI: http://www.mssti.com/
 * License: GPL2
 */

/** phpbb Header
 * 
 * @package: phpBB 3.0.8 :: BRIDGE phpBB & WordPress -> WordPress root/wp-content/plugins
 * @version: $Id: wp_phpbb3_bridge_options.php, v0.0.4 2011/07/04 11:07:04 leviatan21 Exp $
 * @copyright: leviatan21 < info@mssti.com > (Gabriel) http://www.mssti.com/phpbb3/
 * @license: http://opensource.org/licenses/gpl-license.php GNU Public License 
 * @author: leviatan21 - http://www.phpbb.com/community/memberlist.php?mode=viewprofile&u=345763
 * 
 */

/**
 * Copyright 2011 leviatan21 (info@mssti.com)
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as 
 * published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/**
* @ignore
**/

// add the admin options page
add_action('admin_menu', 'wp_phpbb3_bridge_admin_add_page');

/**
 * create custom plugin settings menu
 * 
 * What this does is quite simple, really:
 *	a. It adds a link under the settings menu called “Custom Plugin Menu”.
 * 	b. When you click it, you go to a page with a title of “Custom Plugin Page”.
 * 	c. You must have the “manage_options” capability to get there though (admins only).
 * 	d. The link this will be will in fact be /wp-admin/options-general.php?page=plugin (so “plugin” needs to be something only you will use).
 * 	e. And the content of the page itself will be generated by the “plugin_options_page” function.
 */
function wp_phpbb3_bridge_admin_add_page()
{
	add_menu_page(
		'BRIDGE phpBB & WordPress Plugin Menu',
		'BRIDGE phpBB & WordPress Plugin Page',
		'manage_options',
		'wp_phpbb3_bridge',
		'wp_phpbb3_bridge_options_page'
	);
}

function wp_phpbb3_bridge_options_page()
{
	// must check that the user has the required capability
	if (!current_user_can('manage_options'))
	{
		wp_die(__('You do not have sufficient permissions to access this page.'));
	}

	$active	= (isset($_GET['wp_phpbb3_bridge'])) ? $_GET['wp_phpbb3_bridge'] : false;
	$path	= (isset($_GET['wp_phpbb_root_path']) && $_GET['wp_phpbb_root_path'] != '') ? trim($_GET['wp_phpbb_root_path']) : '../phpBB/';

	// Some default options
	$submit	= (isset($_POST['submit'])) ? true : false;
	$active	= get_option('wp_phpbb3_bridge', $active);
	$path	= get_option('wp_phpbb_root_path', $path);

	if ($submit)
	{
		$active	= (isset($_POST['wp_phpbb3_bridge'])) ? $_POST['wp_phpbb3_bridge'] : $active;

		$path	= (isset($_POST['wp_phpbb_root_path']) && $_POST['wp_phpbb_root_path'] != '') ? trim($_POST['wp_phpbb_root_path']) : $path;

		// Remove any repeated slashes
		$path = preg_replace('#/{2,}#', '/', $path);

		// Add closing / if not present
		$path = ($path && substr($path, -1) != '/') ? $path . '/' : $path;
	}

	// We test the path againt '../' because we are in the admin folder ;)
	if (!@file_exists('../' . $path . 'config.php') || (@!is_dir('../' . $path) && is_file('../' . $path)))
	{
		$active = false;
		$submit = false;
?>
		<div id="message" class="error fade" style="padding: .5em; background-color: #BC2A4D; color: #FFFFFF; font-weight: bold;">
			<p> <?php _e("Could not find path to your former board. Please check your settings and try again.<br />» <samp>$path</samp> was specified as the source path.<br /><br />Cannot activate bridge.", 'wp_phpbb3_bridge'); ?> </p>
		</div>
<?php
	}

	if ($submit)
	{
		update_option('wp_phpbb3_bridge', $active);
		update_option('wp_phpbb_root_path', $path);
?>
		<div id="message" class="updated fade" style="padding: .5em; background-color: #228822; color: #FFFFFF; font-weight: bold;">
			<p> <?php _e('Options saved.', 'wp_phpbb_bridge'); ?> </p>
		</div>
<?php
	}
?>
	<div class="wrap">
		<form method="post" action="">
			<h2><img class="icon16" src="<?php echo esc_url( admin_url('images/generic.png')); ?>" /> BRIDGE phpBB & WordPress</h2>
			<table class="form-table">
				<tr>
					<th>
						<label for="wp_phpbb3_bridge"> <?php _e('Enable Bridge:', 'wp_phpbb3_bridge'); ?></label>
					</th>
					<td>
						<input type="radio" name="wp_phpbb3_bridge" value="1" <?php echo (($active) ? 'id="wp_phpbb3_bridge" checked="checked" ' : '') ?> /> <?php _e('Yes', 'wp_phpbb3_bridge'); ?>
						&nbsp;
						<input type="radio" name="wp_phpbb3_bridge" value="0" <?php echo ((!$active) ? 'id="wp_phpbb3_bridge" checked="checked" ' : '') ?> /> <?php _e('No', 'wp_phpbb3_bridge'); ?>
						<br />
						<span class="description"><?php _e('This will make the Bridge unavailable to use.', 'wp_phpbb3_bridge'); ?></span>
					</td>
				</tr>
				<tr>
					<th>
						<label for="wp_phpbb_root_path"> <?php _e('Path to phpBB:', 'wp_phpbb3_bridge'); ?></label>
					</th>
					<td>
						<input type="text" name="wp_phpbb_root_path" style="width: 95%" value="<?php echo $path; ?>" />
						<br />
						<span class="description"><?php _e('The path where phpBB is located <strong>relative</strong> to the domain name, e.g. <samp>../phpBB3/</samp>.', 'wp_phpbb3_bridge'); ?></span>
						<br />
						<?php _e('<b>Example :</b> <samp>"../phpBB/</samp>"<br />The Blog is at: <samp>http://www.mydomain.tld/wordpress/</samp><br />The Forum is at: <samp>http://www.example.com/phpBB/</samp>', 'wp_phpbb3_bridge'); ?>
					</td>
				</tr>
			</table>
			<?php submit_button(null, 'primary', 'submit');  ?>
		</form>
	</div>

<?php
	wp_phpbb3_bridge_template($active);
}

function wp_phpbb3_bridge_template($active = true)
{
	$error	 = false;
	$message = '';
	$action	 = '';
	$theme	 = strtolower(get_option('template'));

	if ($active)
	{
		if ($theme != 'prosilver')
		{
			$error = true;
			$message .= __('The "Prosilver" theme is deactivated', 'wp_phpbb3_bridge');

			if (current_user_can('switch_themes'))
			{
				$redir = admin_url('themes.php');
				$action .= '<a href="' . $redir . '" title="' . esc_attr__('Activate theme', '') . '" style="color: #FFFFFF; font-weight: bold;">' . __('Activate theme', 'wp_phpbb3_bridge') . '</a>';
			}
			else
			{
				$action .= __('Please notify the system administrator or webmaster', 'wp_phpbb3_bridge');		
			}
		}	
	}
	else
	{
		if ($theme == 'prosilver')
		{
			$error = true;
			$message .= __('The "Prosilver" theme is activated', 'wp_phpbb3_bridge');

			if (current_user_can('switch_themes'))
			{
				$redir = admin_url('themes.php');
				$action .= '<a href="' . $redir . '" title="' . esc_attr__('Deactivate theme', '') . '" style="color: #FFFFFF; font-weight: bold;">' . __('Deactivate theme', 'wp_phpbb3_bridge') . '</a>';
			}
			else
			{
				$action .= __('Please notify the system administrator or webmaster', 'wp_phpbb3_bridge');		
			}
		}		
	}

	if ($error)
	{
		echo '<div id="message" class="error fade" style="padding: .5em; background-color: #BC2A4D; color: #FFFFFF; font-weight: bold;">
			<p>' . $message . '<br />' . $action . '</p>
		</div>';
	}
}

?>